apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        track: production
    spec:
      containers:
        - name: backend
          image: "chesser:1.0.0"
          ports:
            - name: backend
              containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        track: production
    spec:
      containers:
        - name: frontend
          image: "chesser-frontend:1.0.0"
          ports:
            - name: frontend
              containerPort: 8080