apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        track: production
    spec:
      containers:
        - name: backend
          image: "759850685393.dkr.ecr.us-west-2.amazonaws.com/chesser-backend:1.0.0"
          imagePullPolicy: Always
          ports:
            - name: backend
              containerPort: 8080
      imagePullSecrets:
        - name: aws
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        track: production
    spec:
      containers:
        - name: frontend
          image: "759850685393.dkr.ecr.us-west-2.amazonaws.com/chesser-frontend:1.0.0"
          imagePullPolicy: Always
          ports:
            - name: frontend
              containerPort: 8080
      imagePullSecrets:
        - name: aws