pipeline {
	agent {
		docker {

		}
	}
	stages {
        stage('Build') {
            steps {
				docker build -t chesser-frontend .
            }
        }

        stage('Tag') {
            steps {
                docker tag chesser-frontend:latest 759850685393.dkr.ecr.us-west-2.amazonaws.com/chesser-frontend:latest
            }
        }

        stage('Push') {
            steps {
                docker push 759850685393.dkr.ecr.us-west-2.amazonaws.com/chesser-frontend:latest
            }
        }
    }
}