pipeline {
	agent any
	stages {
        stage('Build Frontend') {
            steps {
                sh 'docker build -t chesser-frontend:1.0.0 frontend'
            }
        }

        stage('Sanity Check') {
            steps {
                sh 'docker images | grep chesser-frontend'
            }
        }
    }
}