pipeline {
    environment {
        registry = "emmanueltelewa/chesser"
        registryCredential = 'dockerhub'
    }
	agent any
	stages {
        stage('Build Frontend') {
            steps {
                sh 'docker build -t chesser-frontend:1.0.0 frontend'
            }
        }

        stage('Sanity Check') {
            steps {
                sh 'docker images | grep chesser-frontend'
            }
        }

        stage('Tag the image!') {
            steps {
                sh 'docker tag chesser-frontend-1-0-0 emmanueltelewa/chesser:chesser-frontend-1-0-0'
            }
        }

        stage('cleanup docker images') {
            steps {
                sh 'docker system prune -f'
            }
        }

        stage('Push the image to dockerhub!') {
            steps {
                sh 'docker push emmanueltelewa/chesser:chesser-frontend-1-0-0'
            }
        }

    }
}