apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        track: production
    spec:
      containers:
        - image: 'emmanueltelewa/chesser:chesser-backend-1-0-0'
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 8080
              name: backend
      imagePullSecrets:
        - name: regcred
