pipeline {
	agent {
	    dockerfile {
	        dir 'backend/chesser'
	    }
	}
	stages {
        stage('Build') {
            steps {
                withEnv(["PATH=$PATH:~/.local/bin"]){
				    sh 'docker images'
				}
            }
        }
    }
}