kind: Deployment
apiVersion: apps/v1
metadata:
    name: backend-deployment
spec:
    replicas: {{.Values.backend.scale}}
    selector:
        matchLabels:
            app: backend-deployment
    template:
        metadata:
            labels:
                app: backend-deployment
                track: production
        spec:
            containers:
                - name: backend-d
                  image: {{.Values.backend.image}}
                  imagePullPolicy: Always
                  ports:
                      - name: backend-d
                        containerPort: {{.Values.backend.containerPort}}
            imagePullSecrets:
                - name: regcred

---
kind: Service
apiVersion: v1
metadata:
    name: backend
spec:
    type: NodePort
    selector:
        app: backend-deployment
    ports:
        - port: {{.Values.backend.port}}
          targetPort: {{.Values.backend.containerPort}} # the port
