kind: Deployment
apiVersion: apps/v1
metadata:
    name: frontend-deployment
spec:
    replicas: {{.Values.frontend.scale}}
    selector:
        matchLabels:
            app: frontend-deployment
    template:
        metadata:
            labels:
                app: frontend-deployment
                track: production
        spec:
            containers:
                - name: frontend-d
                  image: {{.Values.frontend.image}}
                  imagePullPolicy: Always
                  ports:
                      - name: frontend-d
                        containerPort: {{.Values.frontend.containerPort}}
            imagePullSecrets:
                - name: regcred

---
kind: Service
apiVersion: v1
metadata:
    name: frontend
spec:
    type: NodePort
    selector:
        app: frontend-deployment
    ports:
        - port: {{.Values.frontend.port}}
          targetPort: {{.Values.frontend.containerPort}} # the port
